<?php

namespace Database\Seeders;

use App\Models\Categorias\CategoriaSegmento;
use App\Models\Clientes\Cliente;
use App\Models\Status\StatusCliente;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $statusMap = collect([
            'Ativo',
            'Em prospeccao',
            'Em onboarding',
            'Inativo',
        ])->mapWithKeys(fn (string $nome) => [
            $nome => StatusCliente::query()->firstOrCreate(['nome' => $nome]),
        ]);

        $segmentoMap = collect([
            'Hospitalar',
            'Diagnostico clinico',
            'Pesquisa academica',
            'Industria farmaceutica',
            'Veterinaria',
            'Controle de qualidade',
            'Distribuidor cientifico',
            'Biobanco',
            'Saude publica',
        ])->mapWithKeys(fn (string $nome) => [
            $nome => CategoriaSegmento::query()->firstOrCreate(['nome' => $nome]),
        ]);

        $clientes = [
            [
                'codigo_interno' => 'CLI-2026-001',
                'razao_social' => 'Hospital Sao Gabriel Diagnosticos Ltda',
                'nome_fantasia' => 'Hospital Sao Gabriel',
                'cnpj' => '12.111.111/0001-01',
                'status' => 'Ativo',
                'segmento' => 'Hospitalar',
                'nome_completo' => 'Marina Costa',
                'cargo' => 'Coordenadora tecnica',
                'email' => 'marina.costa@saogabriel.lab.br',
                'telefone' => '(11) 98765-1001',
                'cep' => '01311-200',
                'uf' => 'SP',
                'logradouro' => 'Av Paulista',
                'numero' => '1800',
                'complemento' => 'Bloco B',
                'bairro' => 'Bela Vista',
                'cidade' => 'Sao Paulo',
                'observacao' => 'Cliente com alta demanda em biologia molecular e interesse em contratos trimestrais.',
            ],
            [
                'codigo_interno' => 'CLI-2026-002',
                'razao_social' => 'Rede VitaLab Analises Clinicas Ltda',
                'nome_fantasia' => 'VitaLab',
                'cnpj' => '12.222.222/0001-02',
                'status' => 'Ativo',
                'segmento' => 'Diagnostico clinico',
                'nome_completo' => 'Renato Figueira',
                'cargo' => 'Gerente comercial',
                'email' => 'renato.figueira@vitalab.com.br',
                'telefone' => '(21) 98765-1002',
                'cep' => '20040-020',
                'uf' => 'RJ',
                'logradouro' => 'Rua do Ouvidor',
                'numero' => '88',
                'complemento' => null,
                'bairro' => 'Centro',
                'cidade' => 'Rio de Janeiro',
                'observacao' => 'Rede com unidades regionais e interesse em padronizacao de kits respiratorios.',
            ],
            [
                'codigo_interno' => 'CLI-2026-003',
                'razao_social' => 'Instituto Atlas de Pesquisa Aplicada',
                'nome_fantasia' => 'Instituto Atlas',
                'cnpj' => '12.333.333/0001-03',
                'status' => 'Em prospeccao',
                'segmento' => 'Pesquisa academica',
                'nome_completo' => 'Paula Freitas',
                'cargo' => 'Pesquisadora associada',
                'email' => 'paula.freitas@atlaspesquisa.org',
                'telefone' => '(31) 98765-1003',
                'cep' => '30140-110',
                'uf' => 'MG',
                'logradouro' => 'Rua da Bahia',
                'numero' => '640',
                'complemento' => 'Laboratorio 4',
                'bairro' => 'Centro',
                'cidade' => 'Belo Horizonte',
                'observacao' => 'Projeto piloto para biomarcadores inflamatorios com potencial de edital publico.',
            ],
            [
                'codigo_interno' => 'CLI-2026-004',
                'razao_social' => 'BioNova Farma Pesquisa e Desenvolvimento S.A.',
                'nome_fantasia' => 'BioNova Farma',
                'cnpj' => '12.444.444/0001-04',
                'status' => 'Em onboarding',
                'segmento' => 'Industria farmaceutica',
                'nome_completo' => 'Leandro Martins',
                'cargo' => 'Head de P&D',
                'email' => 'leandro.martins@bionovafarma.com',
                'telefone' => '(19) 98765-1004',
                'cep' => '13092-500',
                'uf' => 'SP',
                'logradouro' => 'Av Carlos Grimaldi',
                'numero' => '1701',
                'complemento' => 'Modulo 3',
                'bairro' => 'Fazenda Santa Candida',
                'cidade' => 'Campinas',
                'observacao' => 'Conta estrategica com ciclo de venda consultivo e forte peso tecnico.',
            ],
            [
                'codigo_interno' => 'CLI-2026-005',
                'razao_social' => 'VetPrime Diagnosticos Veterinarios Ltda',
                'nome_fantasia' => 'VetPrime',
                'cnpj' => '12.555.555/0001-05',
                'status' => 'Ativo',
                'segmento' => 'Veterinaria',
                'nome_completo' => 'Ana Luiza Prado',
                'cargo' => 'Diretora de laboratorio',
                'email' => 'ana.prado@vetprime.com.br',
                'telefone' => '(41) 98765-1005',
                'cep' => '80250-180',
                'uf' => 'PR',
                'logradouro' => 'Rua Brasilio Itibere',
                'numero' => '901',
                'complemento' => null,
                'bairro' => 'Agua Verde',
                'cidade' => 'Curitiba',
                'observacao' => 'Cliente aberto a pilotos, mas com orcamento muito sensivel ao trimestre.',
            ],
            [
                'codigo_interno' => 'CLI-2026-006',
                'razao_social' => 'NeoQuality Controle de Alimentos Ltda',
                'nome_fantasia' => 'NeoQuality',
                'cnpj' => '12.666.666/0001-06',
                'status' => 'Em prospeccao',
                'segmento' => 'Controle de qualidade',
                'nome_completo' => 'Rafaela Moura',
                'cargo' => 'Supervisora de qualidade',
                'email' => 'rafaela.moura@neoquality.com.br',
                'telefone' => '(51) 98765-1006',
                'cep' => '90560-002',
                'uf' => 'RS',
                'logradouro' => 'Av Nilo Pecanha',
                'numero' => '3200',
                'complemento' => 'Sala 12',
                'bairro' => 'Tres Figueiras',
                'cidade' => 'Porto Alegre',
                'observacao' => 'Busca resposta rapida para lotes de controles positivos em auditorias.',
            ],
            [
                'codigo_interno' => 'CLI-2026-007',
                'razao_social' => 'Hemocentro Vale Sul',
                'nome_fantasia' => 'Hemocentro Vale Sul',
                'cnpj' => '12.777.777/0001-07',
                'status' => 'Ativo',
                'segmento' => 'Saude publica',
                'nome_completo' => 'Carlos Teles',
                'cargo' => 'Coordenador operacional',
                'email' => 'carlos.teles@hemovalesul.gov.br',
                'telefone' => '(12) 98765-1007',
                'cep' => '12245-530',
                'uf' => 'SP',
                'logradouro' => 'Av Cassiano Ricardo',
                'numero' => '420',
                'complemento' => null,
                'bairro' => 'Jardim Aquarius',
                'cidade' => 'Sao Jose dos Campos',
                'observacao' => 'Equipe focada em rastreabilidade de coleta e reducao de retrabalho.',
            ],
            [
                'codigo_interno' => 'CLI-2026-008',
                'razao_social' => 'GenomaHub Distribuicao Cientifica Ltda',
                'nome_fantasia' => 'GenomaHub',
                'cnpj' => '12.888.888/0001-08',
                'status' => 'Inativo',
                'segmento' => 'Distribuidor cientifico',
                'nome_completo' => 'Bruno Siqueira',
                'cargo' => 'Gerente de produto',
                'email' => 'bruno.siqueira@genomahub.com',
                'telefone' => '(11) 98765-1008',
                'cep' => '04551-010',
                'uf' => 'SP',
                'logradouro' => 'Rua Gomes de Carvalho',
                'numero' => '1507',
                'complemento' => 'Conjunto 61',
                'bairro' => 'Vila Olimpia',
                'cidade' => 'Sao Paulo',
                'observacao' => 'Conta pausada apos perda para concorrente com janela logistica mais curta.',
            ],
            [
                'codigo_interno' => 'CLI-2026-009',
                'razao_social' => 'Centro Universitario Serra Azul',
                'nome_fantasia' => 'Serra Azul',
                'cnpj' => '12.999.999/0001-09',
                'status' => 'Em prospeccao',
                'segmento' => 'Pesquisa academica',
                'nome_completo' => 'Luciana Reis',
                'cargo' => 'Professora pesquisadora',
                'email' => 'luciana.reis@serraazul.edu.br',
                'telefone' => '(27) 98765-1009',
                'cep' => '29055-450',
                'uf' => 'ES',
                'logradouro' => 'Av Nossa Senhora da Penha',
                'numero' => '699',
                'complemento' => 'Predio C',
                'bairro' => 'Santa Lucia',
                'cidade' => 'Vitoria',
                'observacao' => 'Projeto depende de revisao de escopo e aprovacao de bolsa complementar.',
            ],
            [
                'codigo_interno' => 'CLI-2026-010',
                'razao_social' => 'Biobanco Horizonte Ltda',
                'nome_fantasia' => 'Biobanco Horizonte',
                'cnpj' => '13.101.101/0001-10',
                'status' => 'Em onboarding',
                'segmento' => 'Biobanco',
                'nome_completo' => 'Tatiane Rocha',
                'cargo' => 'Gestora de operacoes',
                'email' => 'tatiane.rocha@biobancohorizonte.com',
                'telefone' => '(61) 98765-1010',
                'cep' => '70790-050',
                'uf' => 'DF',
                'logradouro' => 'SIA Trecho 4',
                'numero' => '120',
                'complemento' => 'Galpao 2',
                'bairro' => 'Zona Industrial',
                'cidade' => 'Brasilia',
                'observacao' => 'Biobanco em expansao com exigencia de rastreio por lote e armazenamento seguro.',
            ],
            [
                'codigo_interno' => 'CLI-2026-011',
                'razao_social' => 'Laboratorio Prisma Molecular Ltda',
                'nome_fantasia' => 'Prisma Molecular',
                'cnpj' => '13.111.111/0001-11',
                'status' => 'Ativo',
                'segmento' => 'Diagnostico clinico',
                'nome_completo' => 'Fabio Lima',
                'cargo' => 'Diretor operacional',
                'email' => 'fabio.lima@prismamolecular.com.br',
                'telefone' => '(85) 98765-1011',
                'cep' => '60160-230',
                'uf' => 'CE',
                'logradouro' => 'Av Dom Luis',
                'numero' => '500',
                'complemento' => 'Sala 1510',
                'bairro' => 'Meireles',
                'cidade' => 'Fortaleza',
                'observacao' => 'Equipe comercial pede revisao de mix entre painel multiplex e meios de transporte.',
            ],
            [
                'codigo_interno' => 'CLI-2026-012',
                'razao_social' => 'Clinica Santa Emilia Imagem e Analises Ltda',
                'nome_fantasia' => 'Santa Emilia',
                'cnpj' => '13.121.121/0001-12',
                'status' => 'Inativo',
                'segmento' => 'Hospitalar',
                'nome_completo' => 'Juliana Araujo',
                'cargo' => 'Compradora',
                'email' => 'juliana.araujo@santaemilia.com.br',
                'telefone' => '(71) 98765-1012',
                'cep' => '41820-021',
                'uf' => 'BA',
                'logradouro' => 'Av Tancredo Neves',
                'numero' => '1189',
                'complemento' => 'Torre Norte',
                'bairro' => 'Caminho das Arvores',
                'cidade' => 'Salvador',
                'observacao' => 'Conta em acompanhamento para nova janela de renovacao no proximo semestre.',
            ],
            [
                'codigo_interno' => 'CLI-2026-013',
                'razao_social' => 'OncoPrime Centro de Diagnostico Ltda',
                'nome_fantasia' => 'OncoPrime',
                'cnpj' => '13.131.131/0001-13',
                'status' => 'Ativo',
                'segmento' => 'Diagnostico clinico',
                'nome_completo' => 'Debora Aguiar',
                'cargo' => 'Coordenadora de patologia molecular',
                'email' => 'debora.aguiar@oncoprime.com.br',
                'telefone' => '(11) 98765-1013',
                'cep' => '04038-003',
                'uf' => 'SP',
                'logradouro' => 'Rua Borges Lagoa',
                'numero' => '1230',
                'complemento' => '5 andar',
                'bairro' => 'Vila Clementino',
                'cidade' => 'Sao Paulo',
                'observacao' => 'Conta madura com potencial para expansao de paineis oncologicos.',
            ],
            [
                'codigo_interno' => 'CLI-2026-014',
                'razao_social' => 'AgroTrace Controle Integrado Ltda',
                'nome_fantasia' => 'AgroTrace',
                'cnpj' => '13.141.141/0001-14',
                'status' => 'Em prospeccao',
                'segmento' => 'Controle de qualidade',
                'nome_completo' => 'Diego Monteiro',
                'cargo' => 'Responsavel por qualidade',
                'email' => 'diego.monteiro@agrotrace.com.br',
                'telefone' => '(62) 98765-1014',
                'cep' => '74810-200',
                'uf' => 'GO',
                'logradouro' => 'Av 136',
                'numero' => '761',
                'complemento' => 'Sala 804',
                'bairro' => 'Setor Sul',
                'cidade' => 'Goiania',
                'observacao' => 'Lead novo com interesse em rastreio de coleta e controle de estabilidade.',
            ],
        ];

        foreach ($clientes as $index => $dados) {
            $cliente = Cliente::query()->firstOrNew([
                'codigo_interno' => $dados['codigo_interno'],
            ]);

            $cliente->fill([
                'razao_social' => $dados['razao_social'],
                'nome_fantasia' => $dados['nome_fantasia'],
                'cnpj' => $dados['cnpj'],
                'id_status_cliente' => $statusMap[$dados['status']]->id,
                'id_categoria_segmento' => $segmentoMap[$dados['segmento']]->id,
                'nome_completo' => $dados['nome_completo'],
                'cargo' => $dados['cargo'],
                'email' => $dados['email'],
                'telefone' => $dados['telefone'],
                'cep' => $dados['cep'],
                'uf' => $dados['uf'],
                'logradouro' => $dados['logradouro'],
                'numero' => $dados['numero'],
                'complemento' => $dados['complemento'],
                'bairro' => $dados['bairro'],
                'cidade' => $dados['cidade'],
                'observacao' => $dados['observacao'],
            ]);

            $cliente->saveQuietly();

            $createdAt = CarbonImmutable::now()->subDays(160 - ($index * 6))->setTime(9, 0);
            $updatedAt = $createdAt->addDays(4);

            $this->syncTimestamps($cliente, $createdAt, $updatedAt);
        }

        $this->command->info('ClienteSeeder concluido com ' . count($clientes) . ' clientes.');
    }

    private function syncTimestamps(Model $model, CarbonImmutable $createdAt, CarbonImmutable $updatedAt): void
    {
        $model->timestamps = false;
        $model->forceFill([
            'created_at' => $createdAt,
            'updated_at' => $updatedAt,
        ])->saveQuietly();
        $model->timestamps = true;
    }
}
